#! /bin/sh

# Carry out specific functions when asked to by the system
case "$1" in
  start)
	sudo sh /opt/cuckoo_saltar/ip_tables.sh 172.25.1.0/24
    ;;
  stop)
    ;;
  *)
    exit 1
    ;;
esac

exit 0
